# Generated by Django 5.1 on 2024-10-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sis_orcamento', '0003_alter_orcamentos_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentos',
            name='problema_pelo_cliente',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
